/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.lab1;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Lab1JFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Lab1JFrame.class.getName());
  
    public Lab1JFrame() {
        initComponents();
};
  
    private double func(double x) {
    return Math.sin(x*x); 
    }
  
    private double computeIntegral(double step, double lowlim, double uplim) {
    if (lowlim >= uplim || step <= 0) {
        throw new IllegalArgumentException("Некорректные параметры: lowlim < uplim, step > 0");
    }

    double sum = 0.0;
    double x = lowlim;
    while (x < uplim) {
        double nextX = x + step;
        // Если следующая точка выходит за b — ограничиваем её значением b
        if (nextX > uplim) {
            nextX = uplim;
        }
        double y1 = func(x);
        double y2 = func(nextX);
        // Площадь трапеции
        sum += (y1 + y2) * (nextX - x) / 2.0;
        x = nextX;
    }
    return sum;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableModel = new javax.swing.JTable();
        CountButton = new javax.swing.JButton();
        ClearStringButton = new javax.swing.JButton();
        AddToTableButton = new javax.swing.JButton();
        StepLabel = new javax.swing.JLabel();
        UpLimitLabel = new javax.swing.JLabel();
        DownLimitLabel = new javax.swing.JLabel();
        StepTextField = new javax.swing.JTextField();
        UpperLimitTextField = new javax.swing.JTextField();
        LowerLimitTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 32)); // NOI18N
        jLabel1.setText("Function is sin(x²)");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TableModel.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        TableModel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TableModel.setForeground(new java.awt.Color(153, 153, 153));
        TableModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Step", "Upper Limit", "Lower Limit", "Count Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableModel.setToolTipText("");
        TableModel.setShowVerticalLines(true);
        jScrollPane1.setViewportView(TableModel);

        CountButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CountButton.setText("Count");
        CountButton.addActionListener(this::CountButtonActionPerformed);

        ClearStringButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ClearStringButton.setText("Clear string");
        ClearStringButton.addActionListener(this::ClearStringButtonActionPerformed);

        AddToTableButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        AddToTableButton.setText("Add to table");
        AddToTableButton.addActionListener(this::AddToTableButtonActionPerformed);

        StepLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        StepLabel.setText("Step:");

        UpLimitLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UpLimitLabel.setText("Upper Limit:");

        DownLimitLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DownLimitLabel.setText("Lower Limit:");

        StepTextField.addActionListener(this::StepTextFieldActionPerformed);

        UpperLimitTextField.addActionListener(this::UpperLimitTextFieldActionPerformed);

        LowerLimitTextField.addActionListener(this::LowerLimitTextFieldActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DownLimitLabel)
                            .addComponent(StepLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LowerLimitTextField)
                            .addComponent(StepTextField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(UpLimitLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpperLimitTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CountButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ClearStringButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddToTableButton)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StepLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DownLimitLabel)
                            .addComponent(LowerLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UpLimitLabel)
                            .addComponent(UpperLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CountButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddToTableButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClearStringButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountButtonActionPerformed
    int selectedRow = TableModel.getSelectedRow(); 
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Выберите строку для вычисления", "Информация", JOptionPane.WARNING_MESSAGE);
        return; 
    }
    try{
        DefaultTableModel model = (DefaultTableModel) TableModel.getModel();
        double step = Double.parseDouble( TableModel.getValueAt(selectedRow, 0).toString());
        double lowlim = Double.parseDouble( TableModel.getValueAt(selectedRow, 1).toString());
        double uplim = Double.parseDouble( TableModel.getValueAt(selectedRow, 2).toString());
        double result = computeIntegral(step, lowlim,uplim);

        // Форматируем результат до 5 знаков
        String formattedResult = String.format("%.5f", result);
        model.setValueAt(formattedResult, selectedRow, 3);
    }
    catch(Exception e){
         JOptionPane.showMessageDialog(this, "Ошибка при вычислении: " + e.getMessage(), "Ошибка", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_CountButtonActionPerformed

    private void ClearStringButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearStringButtonActionPerformed
        int selectedRow = TableModel.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Выберите строку для удаления", "Информация", JOptionPane.WARNING_MESSAGE);
        return;
    }
    // получаем модель и удаляем строку
    DefaultTableModel model = (DefaultTableModel) TableModel.getModel();
    model.removeRow(selectedRow);
    }//GEN-LAST:event_ClearStringButtonActionPerformed

    private void UpperLimitTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpperLimitTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpperLimitTextFieldActionPerformed

    private void LowerLimitTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LowerLimitTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LowerLimitTextFieldActionPerformed

    private void AddToTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToTableButtonActionPerformed
        try {
            double step = Double.parseDouble(StepTextField.getText());
            double lowlim = Double.parseDouble(LowerLimitTextField.getText());
            double uplim = Double.parseDouble(UpperLimitTextField.getText());
            
             // Проверка корректности: lowlim < uplim, step > 0 и т.д.
        if (lowlim >= uplim || step <= 0) {
            JOptionPane.showMessageDialog(this, "Некорректные параметры: lowlim < uplim, step > 0", "Ошибка", JOptionPane.ERROR_MESSAGE);
            return;
        }
         // получаем модель и добавляем строку
        DefaultTableModel model = (DefaultTableModel) TableModel.getModel();
        model.addRow(new Object[]{step, lowlim, uplim, ""});
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Введите корректные числа", "Ошибка", JOptionPane.ERROR_MESSAGE);
        };
    }//GEN-LAST:event_AddToTableButtonActionPerformed

    private void StepTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StepTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StepTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Lab1JFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToTableButton;
    private javax.swing.JButton ClearStringButton;
    private javax.swing.JButton CountButton;
    private javax.swing.JLabel DownLimitLabel;
    private javax.swing.JTextField LowerLimitTextField;
    private javax.swing.JLabel StepLabel;
    private javax.swing.JTextField StepTextField;
    private javax.swing.JTable TableModel;
    private javax.swing.JLabel UpLimitLabel;
    private javax.swing.JTextField UpperLimitTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
